input.onButtonPressed(Button.AB, function () {
    music.playTone(784, music.beat(BeatFraction.Breve))
    music.playTone(740, music.beat(BeatFraction.Double))
    music.playTone(988, music.beat(BeatFraction.Double))
    music.playTone(659, music.beat(BeatFraction.Breve))
    music.playTone(587, music.beat(BeatFraction.Double))
    music.playTone(784, music.beat(BeatFraction.Double))
    music.playTone(523, music.beat(BeatFraction.Double))
})
basic.showString("Welcomne to the Black Parade")
